app/models.py
from app import db

class User(db.Model):
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)

    def __repr__(self):
        return f'User: {self.username}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email


class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Register')

app/__init__.py
from flask import Flask 
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app import models

app/blueprints/main/__init__.py
from flask import Blueprint 

bp = Blueprint('main', __name__)

from app.blueprints.main import routes 

app/blueprints/main/routes.py
from flask import render_template

from . import bp 

@bp.route('/')
def home():
    matrix={
        'cars': ['Ford Mustang', 'Chevrolet Corvette', 'Audi R8', 'Porsche-911'],
        'drivers':['Jeff Gordon', 'Alain Prost', 'Jimmie Johnson', 'Richard Petty', 'Nigel Mansell', 'Michael Schumacher']
    }
    return render_template('index.jinja', title='Home', cars=matrix['cars'], drivers=matrix['drivers'])


@bp.route('/about')
def about():
    return render_template('about.jinja')

app/templates/about.jinja
{% extends "base.jinja" %}
{% block content %}

<h3 style="color:aquamarine;">About us</h3>

<p>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias fugiat obcaecati illum adipisci! </p>
<p>
Odio rem, ullam vero dicta repudiandae porro atque reprehenderit labore consectetur officia numquam molestiae vel corrupti provident?
</p>

{% endblock %}

app/templates/base.jinja
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
  <style>
    p  {
  color:aquamarine;
  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-size: 150%;
}

</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Matrix Cars</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static',filename='main.css') }}">
  </head>
  <body>
    {% include "navbar.jinja" %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <h1 style="color:brown">Welcome To Matrix-Cars!</h1>
    <img src="{{ url_for('static',filename='back1.jpg') }}" alt="" width="400" height="200">

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.jinja
{% extends "base.jinja" %}

{% block content %}

<h3>Cars</h3>
{% for car in cars %}
<p>{{ car }}</p>
{% endfor %}
<h3>Drivers</h3>
{% for driver in drivers %}
<p>{{ driver }}</p>
{% endfor %}

{% endblock %}

app/templates/navbar.jinja
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" style="color:bisque;">Matrix Cars</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}" style="color:bisque;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}" style="color:bisque;">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.signin') }}" style="color:bisque;">Signin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}" style="color:bisque;">About us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/register.jinja
{% extends "base.jinja" %}

{% block content %}
<form action="" method="post">

<h4>Register Now</h4>
{{ form.hidden_tag() }}
<p>
    {{ form.username.label }}
    {{ form.username(size=35) }}
</p>
<p>
    {{ form.email.label }}
    {{ form.email(size=35) }}
    {% for error in form.email.errors %}
        <span>{{ error }}</span>
    {% endfor %}
</p>
<p>
    {{ form.password.label }}
    {{ form.password(size=35) }}
    {% for error in form.password.errors %}
        <span>{{ error }}</span>
    {% endfor %}
</p>
<p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/signin.jinja
{% extends "base.jinja" %}
{% block content %}

<h3>Signin</h3>


{% endblock %}